export const inputData = {
    nameTitle: 'Mrs',
    firstName: 'Aurora',
    lastName: 'Swift',
    dayOfBirth: '07',
    monthOfBirth: '07',
    yearOfBirth: '1997',
    numberOfKids: '1',
    postCode: 'IV3 8AU',
    fullAddress: 'Loch Ness Lodge, Loch Ness Side, Inverness',
    firstAddressLine: 'Loch Ness Lodge',
    secondAddressLine: 'Loch Ness Side',
    city: 'Inverness',
    emailAddress: 'test@test.com',
    mobileNumber: '07741157789',
    employmentStatus: 'Homemaker',
    drivingLicenceType: 'Full UK Car Licence',
    yearsOfHavingLicence: '7',
    yearsOfNoClaimsDiscount: '7',
    incidentType: 'Windscreen',
    incidentMonth: '08',
    incidentYear: '2023',
    wrongIncidentYear: '2013',
    coverStartDateDelayInDays: 5,
    voluntaryExcessAmount: 200,
    paymentFrequency: 'Monthly'
}

export const opelCarData = {
    plateNumber: 'AB12CDE',
    carName: 'VAUXHALL ASTRA SRI TURBO 150',
    yearOfManufacture: '2017',
    transmissionType: 'Manual',
    imported: 'No',
    engineSize: '1399cc',
    fuelType: 'Petrol',
    steering: 'Right-hand',
    estimatedMileage: '10000',
}