name: Cypress tests for ByMiles

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run Cypress tests
      run: npm run cy:run

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mochawesome-report
        path: cypress/reports/

    - name: Download and Extract Artifact
      uses: actions/download-artifact@v4
      with:
        name: mochawesome-report
        path: cypress/reports/

    - name: Generate HTML Report
      run: npx marge cypress/reports/*.json -o cypress/reports

    - name: Deploy
      run: |
        shopt -s dotglob
        cp -r /home/runner/work/qa-test-bymiles/qa-test-bymiles/cypress/reports/* /home/runner/actions_github_pages_1708546242444
        shopt -u dotglob
      working-directory: /home/runner/actions_github_pages_1708546242444
