name: Cypress tests for ByMiles

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'  # Set the desired Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run Cypress tests
      run: npm run cy:run

    - name: Generate Mochawesome report
      run: npm run generate-mochawesome-report

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mochawesome-report
        path: cypress/reports/mochawesome
